github: [https://github.com/vignesh1507]
patreon: patreon.com/Asvix
open_collective: vignesh-skanda
ko_fi: vigneshskanda
community_bridge: Medibot-ai
liberapay: vigneshskanda
lfx_crowdfunding: Medibot-ai
polar: asvix
buy_me_a_coffee: vigneshskanda
thanks_dev: vignesh1507
custom: ['https://razorpay.me/@asvix']
